version: "3.8"
services:
  mysql-standalone:
    image: mysql
    restart: unless-stopped
    ports:
      - "3305:3306"
    environment:
      MYSQL_DATABASE: cs590-sa
      MYSQL_ROOT_PASSWORD: root1234
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
  app:
    build: .
    ports:
    - "8086:8086"
    depends_on:
      mysql-standalone:
        condition: service_healthy